### ISSUE TITLE
Is it available for Apple M1 cpu?

### ISSUE THREAD

**Issue by shnapz** [pishen/annoy4s#17]
1. On the laptop with Apple M1 cpu trying to instantiate `annoy4s.Annoy` and getting `java.lang.UnsatisfiedLinkError`.
2. Following the guide on the main page:
- `sbt compileNative` results in:
```
[info] Loading global plugins from /Users/akabas/.sbt/1.0/plugins
[info] Loading settings for project annoy4s-build from plugins.sbt ...
[info] Loading project definition from /Users/akabas/repos/annoy4s/project
[info] Loading settings for project root from build.sbt ...
[info] Set current project to annoy4s (in build file:/Users/akabas/repos/annoy4s/)
g++ -o /Users/akabas/repos/annoy4s/src/main/resources/darwin/libannoy.dylib -shared -dynamiclib /Users/akabas/repos/annoy4s/src/main/cpp/annoyjava.cpp
In file included from /Users/akabas/repos/annoy4s/src/main/cpp/annoyjava.cpp:15:
/Users/akabas/repos/annoy4s/src/main/cpp/annoylib.h:107:9: warning: Using no AVX instructions [-W#pragma-messages]
#pragma message "Using no AVX instructions"
        ^
1 warning generated.
[success] Total time: 1 s, completed Oct 14, 2022, 2:10:42 PM
```
- `sbt test` results in:
```
[error] Uncaught exception when running annoy4s.AnnoySpec: java.lang.UnsatisfiedLinkError: Can't load library: /Users/*******/Library/Caches/JNA/temp/jna4858349749797659803.tmp
[error] sbt.ForkMain$ForkError: java.lang.UnsatisfiedLinkError: Can't load library: /Users/*******/Library/Caches/JNA/temp/jna4858349749797659803.tmp
[error] 	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2633)
[error] 	at java.base/java.lang.Runtime.load0(Runtime.java:768)
[error] 	at java.base/java.lang.System.load(System.java:1837)
[error] 	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1018)
[error] 	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:988)
[error] 	at com.sun.jna.Native.<clinit>(Native.java:195)
[error] 	at annoy4s.Annoy$.<clinit>(Annoy.scala:100)
[error] 	at annoy4s.AnnoySpec.$anonfun$new$1(AnnoySpec.scala:94)
[error] 	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
```
- Next `sbt publishLocal` succeeds, but then `java.lang.UnsatisfiedLinkError` still persists, so native library is absent.

Looks like the original [spotify/annoy](https://github.com/spotify/annoy) does not support Apple M1? What steps should be taken to fix it?

This issue causes [scio#4515](https://github.com/spotify/scio/issues/4515)

**Comment by pishen** [comment]
How about upgrading [JNA](https://github.com/java-native-access/jna) to newer version? Sorry I don't have an Apple M1 around to reproduce this.
https://github.com/annoy4s/annoy4s/blob/3744055126d27789f2b64a4d5310318f8d585413/build.sbt#L12

**Comment by shnapz** [comment]
> How about upgrading [JNA](https://github.com/java-native-access/jna) to newer version? Sorry I don't have an Apple M1 around to reproduce this.
> 
> https://github.com/annoy4s/annoy4s/blob/3744055126d27789f2b64a4d5310318f8d585413/build.sbt#L12

Wow! Thanks a lot @pishen, it fixes the problem in both annoy4s and scio:
https://github.com/annoy4s/annoy4s/pull/18

**Comment by mridang** [comment]
@shnapz would you know how we can tweak the build to generate a multi-arch build? At work, our developer machines are x86, ARM (M1) and on production we use x86 or ARM (Gravitron).

**Comment by shnapz** [comment]
@mridang I am not sure about this. Definitely when it is build and published on M1 it works after that PR.

I guess that [.travis.yml](https://github.com/annoy4s/annoy4s/blob/master/.travis.yml) should be modified for multiple architectures support. @pishen what do you think?

**Comment by pishen** [comment]
Since the file is located at `src/main/resources/darwin/libannoy.dylib` for both M1 and non-M1, maybe it's not possible to provide a pre-built library for both cases? Is the `libannoy.dylib` file generated on M1 machine also working on non-M1 machine after we upgraded JNA?
